# Copyright 2013, Niklas Hauser
# Copyright 2016, Fabian Greif
# SPDX-License-Identifier: MPL-2.0

import logging
from pathlib import Path

from lxml import etree

LOGGER = logging.getLogger(__name__)


def _to_etree(tree) -> etree.Element:
    assert tree.name == "device"

    root = etree.Element("modm")
    root.set("version", "0.4.0")
    root.append(
        etree.Comment(
            " WARNING: This file is generated by the modm device file generator. Do not edit! "
        )
    )
    device = etree.SubElement(root, tree.name)
    schema = etree.Element("naming-schema")
    schema.text = tree.ids.naming_schema
    device.append(schema)
    # compute all invalid identifier string combinations and choose the shorter list
    invalid = sorted([did.string for did in tree.ids.product() if did not in tree.ids])
    valid = sorted([did.string for did in tree.ids])
    invalid_list = len(invalid) < len(valid)
    for did in invalid if invalid_list else valid:
        dev = etree.Element("invalid-device" if invalid_list else "valid-device")
        dev.text = did
        device.append(dev)

    root_ids = tree.ids
    for k in root_ids.keys():
        device.set(k, "|".join(root_ids.getAttribute(k)))
    for child in tree.children:
        _to_etree_iter(root_ids, child, device)
    return root


def _to_etree_iter(root_ids, tree, parent):
    diffs = tree.ids.minimal_subtract_set(root_ids, tree.parent.ids)

    for diff in diffs:
        me = etree.SubElement(parent, tree.name)
        # sort diff keys in root_id order
        rootkeys = root_ids.keys()
        diffkeys = sorted(
            ((rootkeys.index(d), d) for d in diff.keys()), key=lambda d: d[0]
        )
        for _, k in diffkeys:
            v = diff.getAttribute(k)
            if len(v) > 0:
                me.set("device-" + k, "|".join(v))

        for k, v in tree.attributes.items():
            if k != "value":
                me.set(k, v)
        if tree["value"] is not None:
            me.set("value", tree["value"])

        for child in tree.children:
            _to_etree_iter(root_ids, child, me)


def format_device_file(tree) -> bytes:
    """
    Formats a (merged) device tree as a modm device file.

    :param tree: The root node of the device tree.
    :return: The XML device file content.
    """
    return etree.tostring(
        _to_etree(tree), encoding="UTF-8", pretty_print=True, xml_declaration=True
    )


def write_device_file(tree, path: Path) -> Path:
    """
    Writes a (merged) device tree to a device file.

    :param tree: The root node of the device tree.
    :param path: The file path to write to.
    :return: The file path.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        LOGGER.warning("Overwriting file '%s'", path.name)
    path.write_bytes(format_device_file(tree))
    return path
