# -*- coding: utf-8 -*-
# Copyright (c) 2013-2016, Niklas Hauser
# Copyright (c)      2016, Fabian Greif
# All rights reserved.

import os
import logging

from lxml import etree

from ..device_tree import DeviceTree

LOGGER = logging.getLogger('dfg.output.xml')

class DeviceFileWriter:
    """ DeviceFileWriter
    Formats a generic tree as a modm device file.
    """

    @staticmethod
    def toEtree(tree):
        assert tree.name == 'device'

        # Add the RCA root element
        root = etree.Element('modm')
        root.set('version', '0.3.2')
        root.append(etree.Comment(" WARNING: This file is generated by the modm device file generator. Do not edit! "))
        # Format the entire tree
        device = etree.SubElement(root, tree.name)
        # Add the naming schema
        schema = etree.Element('naming-schema')
        schema.text = tree.ids.naming_schema
        device.append(schema)
        # compute all invalid identifier string combinations
        invalid = sorted([did.string for did in tree.ids.product() if did not in tree.ids])
        valid = sorted([did.string for did in tree.ids])
        # choose the shorter list
        invalid_list = (len(invalid) < len(valid))
        for did in (invalid if invalid_list else valid):
            dev = etree.Element('invalid-device' if invalid_list else 'valid-device')
            dev.text = did
            device.append(dev)

        DeviceFileWriter._to_etree(tree.ids, tree, device)

        return root

    @staticmethod
    def _to_etree(root_ids, tree, me):
        if tree.parent is None:
            diff = tree.ids
        else:
            diff = tree.ids.minimal_subtract(root_ids, tree.parent.ids)

        for k in diff.keys():
            v = diff.getAttribute(k)
            if me.tag != 'device':
                k = 'device-' + k
            if len(v) > 0:
                me.set(k, "|".join(v))

        for k,v in tree.attributes.items():
            if k != 'value':
                me.set(k, v)
        if tree['value'] is not None:
            me.set('value', tree['value'])

        for child in tree.children:
            ch = etree.SubElement(me, child.name)
            DeviceFileWriter._to_etree(root_ids, child, ch)

    @staticmethod
    def format(tree):
        return etree.tostring(DeviceFileWriter.toEtree(tree),
                              encoding="UTF-8",
                              pretty_print=True,
                              xml_declaration=True)

    @staticmethod
    def write(tree, folder, name):
        path = os.path.join(folder, name(tree.ids) + '.xml')
        if os.path.exists(path):
            LOGGER.warning("Overwriting file '%s'", os.path.basename(path))
        else:
            LOGGER.info("New XML file: '%s'", os.path.basename(path))

        with open(path, 'w') as device_file:
            device_file.write(DeviceFileWriter.format(tree).decode('utf-8'))
