#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import argparse
import sys

import glob

rootpath = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..")
sys.path.append(rootpath)

import modm.pkg
import modm.parser

if __name__ == '__main__':

    arg = argparse.ArgumentParser(description='Device Platform Generator')
    arg.add_argument('-i', '--input', dest='input', required=True, help='XML device description.')
    arg.add_argument('-o', '--output', dest='output', required=True, help='Output folder')

    args = arg.parse_args()

    try:
        device_count = 0
        device_files = glob.glob(os.path.join(args.input, "devices/**/*.xml"))
        for device_file in device_files:
            print(device_file)
            parser = modm.parser.DeviceParser(device_file)
            devices = parser.get_devices()

            device_count += len(devices)
            for d in devices:
                print(d)
        # print(device_count)

        # driver_files = glob.glob(os.path.join(args.input, "driver/**/*.xml"), recursive=True)
        driver_files = glob.glob(os.path.join(args.input, "driver/**/*.xml"))
        for driver_file in driver_files:
        #    print(driver_file)
            parser = modm.parser.DriverParser(driver_file)

    except (modm.ParserException) as e:
        print(e)
        exit(1)
