name: Generate

# Generates the device files every week with the latest modm-data to check that
# the committed device files are still up-to-date. They are updated manually.

on:
  schedule:
    - cron:  '23 7 * * 1'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  generate:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # This partitioning has the shortest overall runtime with the fewest jobs
      matrix:
        include:
          - name: "STM32: F4, G4, L0, H5"
            sources: clone-sources-stmicro download-stmicro-cubemx
            targets: stm32f4 stm32g4 stm32l0 stm32h5
          - name: "STM32: C0, G0, U0, H7, L4"
            sources: clone-sources-stmicro download-stmicro-cubemx
            targets: stm32c0 stm32g0 stm32u0 stm32h7 stm32l4
          - name: "STM32: F0, F1, F2, F3, F7, L1, L5, WB, WL, U3, U5"
            sources: clone-sources-stmicro download-stmicro-cubemx
            targets: stm32f0 stm32f1 stm32f2 stm32f3 stm32f7 stm32l1 stm32wb stm32wl stm32u3 stm32u5 stm32l5
          - name: "AVR, SAM, NRF, RP"
            sources: download-sources-microchip clone-sources-nordic download-sources-raspberrypi
            targets: avr sam nrf rp
            tests: true
    steps:
      - name: Check out modm-devices
        uses: actions/checkout@v7
        with:
          path: modm-devices

      - name: Check out modm-data
        uses: actions/checkout@v7
        with:
          repository: modm-io/modm-data
          ref: main
          path: modm-data

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install modm-data
        run: |
          python -m pip install --upgrade pip
          pip install -r modm-data/tools/requirements.txt -e modm-data

      - name: Download modm-data Input Sources
        working-directory: modm-data
        run: |
          make ${{ matrix.sources }}

      - name: Run Parser Tests
        if: matrix.tests
        working-directory: modm-devices
        run: |
          make test

      - name: Run Generator Tests
        if: matrix.tests && !cancelled()
        working-directory: modm-devices
        run: |
          make -C tools/generator test

      - name: Generate Device Files
        if: ${{ !cancelled() }}
        working-directory: modm-devices/tools/generator
        run: |
          python3 -m dfg ${{ matrix.targets }}

      - name: Check Device Files and Docs
        if: ${{ !cancelled() }}
        working-directory: modm-devices
        run: |
          python3 tools/scripts/sync_docs.py
          git status --porcelain
          git diff --stat
          git diff
          test -z "$(git status --porcelain)"

  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Re-enable workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: sh
        run: |
          case "${GITHUB_WORKFLOW_REF:?}" in
            "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
            *) false ;;
          esac
          workflow="${GITHUB_WORKFLOW_REF%%@*}"
          workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
          gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"
